# OBJX Intelligence Platform - Docker Compose Configuration
# Author: Manus AI
# Date: July 25, 2025
# Version: 1.0 - Production Ready

version: '3.8'

services:
  objx-intelligence:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - objx-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - objx-intelligence
    restart: unless-stopped
    networks:
      - objx-network

networks:
  objx-network:
    driver: bridge

volumes:
  objx-data:
    driver: local
  objx-logs:
    driver: local

